### ISSUE TITLE
using s3-compatible minio as backend

### ISSUE THREAD

**Issue by Reasno** [agentejo/CloudStorage#2]
I am using self-hosted minio (which implements full s3 compatible interface) as the backend storage. Since I was allowed to set my custom url in the config, I assumed minio should just work out of box. However I encountered a hard-coded url in the lib when I tried to upload to minio.

```html
<br />
<b>Fatal error</b>:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing &quot;ListObjects&quot; on &quot;https://xy-production.s3.cn-foshan-1.amazonaws.com.cn/?prefix=cockpit%2F2018%2F06%2F28%2F5b348ebac5e21php%2F&amp;max-keys=1&amp;encoding-type=url&quot;; AWS HTTP error: cURL error 6: Could not resolve host: xy-production.s3.cn-foshan-1.amazonaws.com.cn (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: xy-production.s3.cn-foshan-1.amazonaws.com.cn (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/addons/CloudStorage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/www/html/addons/CloudStorage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/addons/CloudStorage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(Guzzl in <b>/var/www/html/addons/CloudStorage/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php</b> on line <b>191</b><br />
```

**Comment by aheinze** [comment]
It seems there is an issue with minio and the original s3 adapter. https://github.com/coraxster/flysystem-aws-s3-v3-minio

**Comment by Reasno** [comment]
It seems to me the referenced issue causes some troubles in certain scenarios, but the root cause of my problem is missing use_path_style_endpoint = true. A [pull request](https://github.com/agentejo/CloudStorage/pull/3) has been submitted so others can see it.
